apiVersion: v1
kind: Service
metadata:
  name: czdns
spec:
  type: NodePort
  selector:
    app: czdns
  ports:
    - name: udp53
      protocol: UDP
      nodePort: 30053
      port: 30053
      targetPort: 53
    - name: tcp53
      protocol: TCP
      nodePort: 30053
      port: 30053
      targetPort: 53
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: czdns
  labels:
    app: czdns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: czdns
  template:
    metadata:
      labels:
        app: czdns
    spec:
      containers:
      - name: czdns
        image: yousong/czdns:v2.0.7
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        ports:
          - containerPort: 53
            protocol: UDP
          - containerPort: 53
            protocol: TCP
        env:
          - name: USE_LIST
            value: chn
          - name: DNSMASQ_EXTRA_CONF
            value: |
              cache-size=40960
              dns-forward-max=4096
