name: Build and push docker image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  schedule:
    #        min hour DoM MoY DoW
    - cron: '0   5    22  *   *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build release
        env:
          VERSION: ${{github.ref_name}}
        run: |
          make release
